repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.min\.css$
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.7.0"
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@2.7.1"
          - "@trivago/prettier-plugin-sort-imports@3.3.0"
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
