# Generated by Django 4.0.10 on 2023-04-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Site Claim Configuration',
            },
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('constellation', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteclaim.constellation')),
                ('region', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteclaim.region')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='constellation',
            name='region',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteclaim.region'),
        ),
    ]
