# Generated by Django 4.0.10 on 2023-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteclaim', '0002_rename_catconfiguration_siteclaimconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteclaimconfiguration',
            name='valid_site_regions',
            field=models.ManyToManyField(blank=True, to='siteclaim.region'),
        ),
    ]
