# Generated by Django 4.0.10 on 2023-04-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteclaim', '0004_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteclaimconfiguration',
            name='site_claim_output_channel',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
