# Generated by Django 4.0.10 on 2023-04-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteclaim', '0005_siteclaimconfiguration_site_claim_output_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteclaimconfiguration',
            name='ess_output_channel',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='siteclaimconfiguration',
            name='ess_ping_at_here',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteclaimconfiguration',
            name='valid_ess_regions',
            field=models.ManyToManyField(
                blank=True, related_name='ess_regions', to='siteclaim.region'),
        ),
        migrations.AlterField(
            model_name='siteclaimconfiguration',
            name='valid_site_regions',
            field=models.ManyToManyField(
                blank=True, related_name='site_regions', to='siteclaim.region'),
        ),
    ]
