# Generated by Django 4.2.5 on 2023-10-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('siteclaim', '0006_siteclaimconfiguration_ess_output_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndyClaim',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_discord', models.CharField(
                    blank=True, default='', max_length=200)),
                ('requested_by_discord_uid', models.BigIntegerField(
                    blank=True, default=None, null=True)),
                ('claimed_by_discord', models.CharField(
                    blank=True, default='', max_length=200)),
                ('claimed_by_discord_uid', models.BigIntegerField(
                    blank=True, default=None, null=True)),
                ('produced_by_notified_by_discord', models.CharField(
                    blank=True, default='', max_length=200)),
                ('produced_by_notified_by_discord_uid', models.BigIntegerField(
                    blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message_id', models.BigIntegerField(
                    blank=True, default=None, null=True)),
                ('interaction_id', models.CharField(max_length=100)),
                ('system_provided', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('claimed_by', models.ForeignKey(blank=True, default=None, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='indys_claimed', to='eveonline.evecharacter')),
                ('produced_by_notified_by', models.ForeignKey(blank=True, default=None, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='indys_notified', to='eveonline.evecharacter')),
                ('requested_by', models.ForeignKey(blank=True, default=None, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, related_name='indys_found', to='eveonline.evecharacter')),
                ('system', models.ForeignKey(blank=True, default=None, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='siteclaim.system')),
            ],
            options={
                'permissions': (('can_request_production', 'Can request production via indy cog'),),
            },
        ),
    ]
