# Generated by Django 4.2.5 on 2023-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteclaim', '0007_indyclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteclaimconfiguration',
            name='indy_claim_output_channel',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
